# permissions for end users to edit serverlessconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serverlessconfiguration-editor-role
rules:
- apiGroups:
  - kyma.kyma-project.io
  resources:
  - serverlessconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kyma.kyma-project.io
  resources:
  - serverlessconfigurations/status
  verbs:
  - get
